# Generated by Django 3.0.4 on 2020-03-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='news_feed',
        ),
        migrations.AddField(
            model_name='post',
            name='news_feed',
            field=models.ManyToManyField(blank=True, to='blog_app.NewsFeed'),
        ),
    ]
