# Generated by Django 3.0.4 on 2020-03-20 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_auto_20200320_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='news_feed',
        ),
        migrations.AddField(
            model_name='post',
            name='news_feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_feeds', to='blog_app.NewsFeed'),
        ),
    ]
